# Generated by Django 6.0.3 on 2026-03-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fisrt_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
